server:
  port: 8400

spring:
  application:
    name: user-management-service
  datasource:
    hikari:
      connectionTimeout: 60000
      maximumPoolSize: 10
    url: jdbc:postgresql://db:5432/dev_01
    username: postgresql
    password: Password
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka