server:
  port: 8100

spring:
  application:
    name: authentication-service
  datasource:
    hikari:
      connectionTimeout: 60000
      maximumPoolSize: 10
    url: jdbc:postgresql://db:5432/dev_01
    username: postgresql
    password: Password
  jpa:
    hibernate:
      ddl-auto: create

eureka:
 client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka