server:
  port: 8100

spring:
  application:
    name: authentication-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/dev_01
    username: ananthupm
    password: Password
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html