version: '3.7'

services:

    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_DB: dev_01
            POSTGRES_USER: postgresql
            POSTGRES_PASSWORD: Password
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - school-network
        volumes:
            - ./../../data:/var/lib/postgresql/data/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgresql"]
            interval: 5s
            timeout: 5s
            retries: 5

    naming-server:
        image: pmananthu/eureka-naming-server:0.1.0
        ports:
            - "8761:8761"
        environment:
            PROFILE: prod
        networks:
            - school-network
            
    hystrix-dashboard:
        image: pmananthu/hystrix-dashboard:0.0.1
        ports:
            - "8300:8300"
        environment:
            PROFILE: prod
        networks:
            - school-network
        depends_on: 
            - naming-server

    api-gateway-service:
        image: pmananthu/api-gateway-service:0.1.1
        ports:
            - "8765:8765"
        environment:
            PROFILE: prod
        networks:
            - school-network
        depends_on: 
            - naming-server

    authentication-service:
        image: pmananthu/authentication-service:0.1.0
        ports:
            - "8100:8100"
        links:
            - "db:db"
        environment:
            PROFILE: prod
        networks:
            - school-network
        depends_on: 
            - naming-server
            - db

    notification-service:
        image: pmananthu/notification-service:0.1.0
        ports:
            - "8200:8200"
            - "587:587"
        environment:
            PROFILE: prod
        networks:
            - school-network
        depends_on: 
            - naming-server

    user-management-service:
        image: pmananthu/user-management-service:0.0.1
        ports:
            - "8400:8400"
        links:
            - "db:db"
        environment:
            PROFILE: prod
        networks:
            - school-network
        depends_on: 
            - naming-server
            - db

    school-management-service:
        image: pmananthu/school-management-service:0.0.1
        ports:
            - "8500:8500"
        links:
            - "db:db"
        environment:
            PROFILE: prod
        networks:
            - school-network
        depends_on: 
            - naming-server
            - db

networks:
    school-network:
