server:
  port: 8100

spring:
  application:
    name: student-management-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/dev_01
    username: ananthupm
    password: Password
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka