server:
  port: 8500

spring:
  application:
    name: school-management-service
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/dev_01
    username: postgresql
    password: Password
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka