server:
  port: 8200

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: skyhawks.app@gmail.com
    password: ppxkfjeifwqqrkga
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka

